[package]
    name = 'filesystem'
    version = '0.1.0'
    edition = '2021'
    description = 'FileSystem utilities'

[lib]
    crate_type = [ 'rlib', 'dylib' ]

[dependencies]
    json = '0.12.4'
    savefile = '0.10.1'
    byteorder = '1.4.3'
    bytes = '1.1.0'
    lzma-rs = '0.2.0'
    libflate = '1.2.0'
    bzip2 = '0.4.3'
    crc32fast = '1.3.0'
    sha256 = '1.0.3'
    path-slash = '0.1.4'
