[package]
name = 'ungine'
version = '0.1.0'
authors = ['ENDERZOMBI102']
edition = '2021'
description = 'A source-inspired game engine'
repository = 'https://github.com/ENDERZOMBI102/Ungine.rs'
license = 'MIT'


[workspace]
resolver='2'
members = [
	'.', 'filesystem', 'renderer', 'richpresence', 'engine_utils', 'engine'
]


[dependencies]
filesystem = { path = 'filesystem' }
renderer = { path = 'renderer' }
richpresence = { path = 'richpresence' }
engine_utils = { path = 'engine_utils' }
engine = { path = 'engine' }
rand = '0.8.4'