[package]
    name = 'richpresence'
    version = '0.1.0'
    edition = '2021'

[lib]
    crate_type = [ 'rlib', 'dylib' ]

[dependencies]
    discord-rich-presence = '0.2.3'
    steamworks = '0.9.0'
    tier0 = { path = '../tier0' }
