[package]
    name = 'uscript'
    version = '0.1.0'
    edition = '2021'
	description = 'Scripting abstraction layer capable of running multiple environments at the same time.'

[lib]
    crate_type = [ 'dylib' ]

[dependencies]
    log = '0.4.17'
	dyon = '0.48.1'
	rhai = '1.12.0'
