[package]
name = 'renderer'
version = '0.1.0'
edition = '2018'
description = 'Ungines Renderer'

[dependencies]
image = '0.23'
winit = '0.25'
cgmath = '0.18'
env_logger = '0.9'
log = '0.4'
wgpu = '0.10.2'
pollster = '0.2'