[package]
    name = 'renderer'
    version = '0.1.0'
    edition = '2021'
    description = 'Ungines Renderer'

[lib]
    crate_type = [ 'rlib', 'dylib' ]

[dependencies]
    image = '0.23.14'
    winit = '0.25'
    cgmath = '0.18'
    log = '0.4.16'
    wgpu = '0.11'
    pollster = '0.2.4'
    bytemuck = { version = '1.4', features = [ 'derive' ] }
    tier0 = { path = '../tier0' }
