[package]
    name = 'angelscript'
    version = '0.1.0'
    edition = '2021'
	description = 'AngelScript implementation for the uscript scripting layer'

[lib]
    crate_type = [ 'dylib' ]

[dependencies]
    log = '0.4.17'
    abi_stable = '0.11.0'
    angelscript = '0.1.1'
