[package]
    name = 'angelscript'
    version = '0.1.0'
    edition = '2021'

[lib]
    crate_type = [ 'rlib', 'dylib' ]

[dependencies]
    log = '0.4.17'
    abi_stable = '0.11.0'
    angelscript = '0.1.1'
